// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbP4casZwQywmK4RVGJouwTOcJ0I2onMM',
    appId: '1:349601331554:web:6546d7824c17d7bc58943b',
    messagingSenderId: '349601331554',
    projectId: 'salesbets-86cf9',
    authDomain: 'salesbets-86cf9.firebaseapp.com',
    storageBucket: 'salesbets-86cf9.firebasestorage.app',
    measurementId: 'G-GSVZ7QV8GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoPWIUoG4zENl6rq1U9dnyhmQQIgfIjCw',
    appId: '1:349601331554:android:230a6e6196253da658943b',
    messagingSenderId: '349601331554',
    projectId: 'salesbets-86cf9',
    storageBucket: 'salesbets-86cf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoUk0L12GO3XFiyD6UJKz60CXPnBhqZE4',
    appId: '1:349601331554:ios:35a903602cadcbc758943b',
    messagingSenderId: '349601331554',
    projectId: 'salesbets-86cf9',
    storageBucket: 'salesbets-86cf9.firebasestorage.app',
    iosBundleId: 'com.example.salesBets',
  );
}
